<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.metalsistem.nonbusinessday</groupId>
  <artifactId>com.metalsistem.nonbusinessday</artifactId>
  <parent>
		<groupId>it.idIta.idempiere.extensions</groupId>
		<artifactId>it.idIta.idempiere.extensions.parent</artifactId>
		<version>13.0.0-SNAPSHOT</version>
		<relativePath>../../idempiere-base/it.idIta.idempiere.extensions.parent/pom.xml</relativePath>
  </parent>
  <packaging>eclipse-plugin</packaging>
  <dependencies>
    <dependency>
	  <groupId>de.focus-shift</groupId>
	  <artifactId>jollyday-core</artifactId>
	  <version>2.21.0</version>
	</dependency>
    <dependency>
      <groupId>de.focus-shift</groupId>
      <artifactId>jollyday-jackson</artifactId>
      <version>2.21.0</version>
    </dependency>
  </dependencies>
  <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>lib</outputDirectory>
							<stripVersion>true</stripVersion>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
